version: '2'
services:
  ddns:
    image: davd/docker-ddns:1.2.1
    restart: unless-stopped
    environment:
      RECORD_TTL: 60
      ZONE: '${DOMAIN}'
      SHARED_SECRET: '${SHARED_SECRET}'
    ports:
      - "${DNS_PORT}:53"
      - "${DNS_PORT}:53/udp"
    volumes:
       - ./data/bind-data:/var/cache/bind
    networks:
      red:
  python:
    image: pyddns:3.1.1
    build: ./docker
    restart: unless-stopped
    volumes:
      - ./appdata/pyddns:/usr/src/app
      - ./appdata/static/node_modules:/usr/src/app/static/node_modules
    environment:
      DNS_HOST: ddns
      DNS_API_PORT: 8080
      DNS_DOMAIN: '${DOMAIN}'
      DNS_SHARED_SECRET: '${SHARED_SECRET}'
      DNS_ALLOW_AGENT: '${DNS_ALLOW_AGENT}'
      LDAP_URI: '${LDAP_URI}'
      LDAP_BIND_DN: '${LDAP_BIND_DN}'
      LDAP_BIND_PASSWD: '${LDAP_BIND_PASSWD}'
      LDAP_BASE_DN: '${LDAP_BASE_DN}'
      DB_HOST: '${DATABASE_HOST}'
      DB_PORT: '${DATABASE_PORT}'
      DB_NAME: '${DATABASE_NAME}'
      DB_USER: '${DATABASE_USER}'
      DB_PASSWORD: '${DATABASE_PASS}'
      DJANGO_ADMIN_URL: '${DJANGO_ADMIN_URL}'
      DJANGO_SU_NAME: '${DJANGO_SU_NAME}'
      DJANGO_SU_EMAIL: '${DJANGO_SU_EMAIL}'
      DJANGO_SU_PASSWORD: '${DJANGO_SU_PASSWORD}'
      OWN_ADMIN: '${OWN_ADMIN}'
      MAX_DOMAINS_USER: '${MAX_DOMAINS_USER}'
    depends_on:
      - "mariadb"
    networks:
      red:

  mariadb:
    image: mariadb:10.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASS}'
      MYSQL_PASSWORD: '${DATABASE_PASS}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
    volumes:
     - ./data/dbdata:/var/lib/mysql
    networks:
      red:

  nginx:
    image: nginx:latest
    ports:
      - "${HTTP_PORT}:8000"
      - "${HTTPS_PORT}:8443"
    volumes:
      - ./config/nginx_src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./appdata/static:/static
      - ./data/certs:/etc/nginx/certs
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - "python"
    networks:
      red:
networks:
  red:

